version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/rest_api
    depends_on:
      - database
    container_name: rest_api-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=rest_api-db'

  database:
    image: mysql:8.0
    container_name: rest_api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: privyTest
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - rest_api-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: rest_api-pma


# persisted storage
volumes:
  rest_api-data:
